---
swagger: "2.0"
info:
  x-ibm-name: "validataelogin"
  title: "validataeLogin"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/validataelogin"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - operation-switch:
        title: "operation-switch"
        case:
        - operations:
          - verb: "post"
            path: "/login"
          execute:
          - gatewayscript:
              title: "gatewayscript"
              version: "1.0.0"
              source: "apim.readInputAsJSON(function(error,buffer) {\r\n    if (error)\
                \ {\r\n        session.output.write(\"Enter valid Credentials\");\r\
                \n    } else if (buffer.userId==='pratap' && buffer.Password==='password'){\r\
                \n        \r\n         session.output.write('{\"Status\":\"Valid user\"\
                }');\r\n    } else {\r\n        session.output.write('{\"Status\"\
                :\"Invalid user\"}');\r\n    }\r\n       \r\n})\r\n apim.output('application/json');"
        otherwise: []
        version: "1.0.0"
    catch:
    - default:
      - gatewayscript:
          title: "gatewayscript"
          version: "1.0.0"
          source: "apim.error('MyError', 500, 'Internal Error', 'unable to respond,\
            \ try again');"
  phase: "realized"
paths:
  /login:
    get:
      responses:
        200:
          description: "200 OK"
    post:
      responses:
        200:
          description: "200 OK"
tags: []
